apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.11.0
  - ../projects/aiops-project.yaml
  - ../applications/root-app.yaml
  - rbac.yaml
patchesStrategicMerge:
  - argocd-cm.yaml